### ISSUE TITLE
iOS 10 crashes...

### ISSUE THREAD

**Issue by speeder** [k06a/MissingAnchors#3]
Sorry for the kinda vague bug report, but I failed to track it down better, I couldn't find what on my program exactly triggers it.

What I did found, is that the bug is that my app crashes upon launching, with this error always:

-[ABLayoutDimension _nearestAncestorLayoutItem]: unrecognized selector sent to instance

Googling _nearestAncestorLayoutItem has only 4 results, I guess it is some new private Apple API...

**Comment by k06a** [comment]
@speeder thanks for reporting!

Are you using iOS7 backport `pod 'MissingAnchors/NSLayoutAnchor'` or only missing anchors?

**Comment by speeder** [comment]
I am using the iOS7 thing yes! In fact this is the whole reason why I am
using MissingAnchors in first place. :)

**Comment by k06a** [comment]
@speeder does this crash happend on iOS10?

**Comment by speeder** [comment]
Yes, only on iOS10, with the error I mentioned.

**Comment by k06a** [comment]
@speeder thanks for reporting! Sorry for crashes in your app!
Check `0.4.5` version – it should be fixed, and close this issue :)

**Comment by k06a** [comment]
@speeder I have no iOS7 device/simulator to check right now, but IMHO this fix should works fine.

**Comment by speeder** [comment]
Good news is: It doesn't crash on iOS10 anymore.

Bad news is: I accidentally installed iOS9 on my iOS7 test device, so I
dunno if it works on iOS7 either :(

**Comment by k06a** [comment]
I think tomorrow I will be able to try it on iOS7

**Comment by speeder** [comment]
My boss tried on an iOS7 decide and an iOS10 device (my test device seemly is half-bricked during the update, so I tested on simulator).

The crash is actually gone.

But the layout is now fucked up, badly, as in, stuff is outright outside the screen O.o

I think this MAYBE is my fault, because I couldn't get your library to compile, and added some "#import <UIKit.h>" in some .h files to make it compile, maybe this is the cause of the layout bug.

I will try to see if I can figure how to compile without the extra imports and see if it still craps out.
